AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - lib/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Rakefile

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
